name: rtdefects
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*
  - flake8
  - jupyterlab
  - pytest
  - pip
  - pip:
     - funcx
     - ratelimit
     - funcx-endpoint
     - tensorflow>2
     - segmentation_models.pytorch==0.2.*
     - torch==1.13.1+cu116  # Using PyPI so we get my locally-installed CUDA
     - -f https://download.pytorch.org/whl/torch_stable.html
     - -e .
