name: rtdefects
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - tensorflow>2
  - watchdog>=2
  - numpy==1.19.*
  - pandas==1.*
  - albumentations==1.0.*
  - scikit-image
  - imageio==2.19.3
  - imageio-ffmpeg
  - trackpy==0.5.*
  - hyperspy-base
  - bokeh
  - flask
  - flask-cors
  - jupyterlab
  - pytest
  - pip
  - pip:
     - funcx
     - ratelimit
     - funcx-endpoint
     - segmentation_models.pytorch
     - torch==1.8.1+cu111  # Using PyPI so we get my locally-installed CUDA
     - -f https://download.pytorch.org/whl/torch_stable.html
     - -e .
